<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>QpdfGui</AssemblyName>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ServerGarbageCollection>false</ServerGarbageCollection>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="FluentIcons.Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Semi.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QpdfGui.Core\QpdfGui.Core.csproj" />
  </ItemGroup>

  <!-- 仅在本地开发调试模式时复制本地 runtimes 目录以便利开发；Release 发布包保持纯净解耦，由用户一键下载或指定 -->
  <ItemGroup Condition="'$(Configuration)' == 'Debug'">
    <None Include="$(MSBuildThisFileDirectory)..\..\runtimes\**" Link="runtimes\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
