<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="FluentIcons.Avalonia" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Semi.Avalonia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\QpdfGui.Core\QpdfGui.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\runtimes\**\*" LinkBase="runtimes" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
